# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: SacprdUserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        admin:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: sacprd_core_login
                check_path: login_check


    access_control:
        - { path: ^/admins, roles: ROLE_ADMIN }

    encoders:
        Sacprd\UserBundle\Entity\User:
            algorithm: md5
            iterations: 1
            encode_as_base64: false
